config/routes.rb
Spree::Core::Engine.routes.draw do
   get 'r/:code' => 'reffiliate#referral', as: 'referral'
  get 'a/:path' => 'reffiliate#affiliate', as: 'affiliate'

  namespace :admin do
    resources :affiliates
  end
end

app/models/spree/affiliate.rb
module Spree
  class Affiliate < Spree::Base
    has_many :referred_records
    
    validates_presence_of :name, :path

    def referred_users
      referred_records.includes(:user).collect(&:user).compact
    end

    def referred_orders
      referred_records.includes({:user => :orders}).collect{|u| u.user.orders }.flatten.compact
    end

    def referred_count
      referred_records.count
    end

    def get_layout
      return false if layout == 'false'
      layout
    end

    private

      def self.layout_options
        [
          ["No Layout", "false"],
          ["Spree Application Layout", 'spree/layouts/spree_application'],
          ["Custom Layout Path", nil]
        ]
      end

      def self.lookup_for_partial lookup_context, partial
        lookup_context.template_exists?(partial, ["spree/affiliates"], false)
      end

  end
end

app/models/spree/promotion/rules/affiliated_promotion_rule.rb
module Spree
  class Promotion
    module Rules
      class AffiliatedPromotionRule < Spree::PromotionRule
        belongs_to :affiliate, :class_name => '::Spree::Affiliate'
        has_and_belongs_to_many :affiliates, :class_name => '::Spree::Affiliate',
          :join_table => 'spree_affiliates_promotion_rules', :foreign_key => 'promotion_rule_id',
          :association_foreign_key => 'affiliate_id'

        def eligible?(order, options = {})
          return true if order.user and order.user.affiliate? and affiliates.collect(&:id).include?(order.user.affiliate.id)
          false
        end

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def affiliate_ids_string
          affiliate_ids.join(',')
        end

        def affiliate_ids_string=(s)
          self.affiliate_ids = s.to_s.split(',').map(&:strip)
        end

        def affiliate_list
          affiliate_ids
        end

        def affiliate_list=(a)
          self.affiliate_ids = a
        end
      end
    end
  end
end

app/models/spree/promotion/rules/referred_promotion_rule.rb
module Spree
  class Promotion
    module Rules
      class ReferredPromotionRule < Spree::PromotionRule
        def eligible?(order, options = {})
          return true if order.user and order.user.referred?
          false
        end
        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end
      end
    end
  end
end

app/models/spree/referral.rb
module Spree
  class Referral < Spree::Base
    belongs_to :user, class_name: Spree.user_class.to_s
    has_many :referred_records

    validates_presence_of :user_id, :code

    before_validation :attach_code, on: :create

    def referred_users
      referred_records.includes(:user).collect(&:user).compact
    end

    def referred_orders
      referred_records_with_user_orders.collect{|u| u.user.orders }.flatten.compact
    end

    def referral_activated_users
      referred_records_with_user_orders.select{|u| post_referral_order?(u) }.collect(&:user)
    end

    protected
      def attach_code
        self.code = loop do
          code =  (0...8).map { (65 + rand(26)).chr }.join
          break code unless Referral.exists?(code: code)
        end
      end

   private

    def referred_records_with_user_orders
      referred_records.includes({:user => :orders})
    end

    def post_referral_order?(referred_record)
      referred_record.user.orders.where('completed_at > ?', self.user.created_at).any?
    end
  end
end

app/models/spree/referred_record.rb
module Spree
  class ReferredRecord < Spree::Base
    belongs_to :referral
    belongs_to :user, class_name: Spree.user_class.to_s
    belongs_to :affiliate

    validates_presence_of :user
  end
end

app/models/spree/user_decorator.rb
module Spree
  Spree.user_class.class_eval do
    has_one :referral
    has_one :referred_record
    has_one :affiliate, through: :referred_record, foreign_key: :affiliate_id
    has_one :affiliate_record, class_name: ReferredRecord

    attr_accessor :referral_code, :affiliate_code

    after_create :create_referral
    after_create :referral_affiliate_check

    def referred_by
      referred_record.try(:referral).try(:user)
    end
    
    def referred_count
      referral.referred_records.count
    end

    def referred?
      !referred_record.try(:referral).try(:user).nil?
    end

    def affiliate?
      !affiliate.nil?
    end

    private
      def referral_affiliate_check
        if !self.referral_code.nil?
          referred = Referral.find_by(code: referral_code)
        elsif !self.affiliate_code.nil?
          referred = Affiliate.find_by(path: affiliate_code)
        end
        if referred
          referred.referred_records.create(user: self)
        end
      end
  end
end

app/controllers/spree/admin/affiliates_controller.rb
module Spree
  module Admin
    class AffiliatesController < Spree::Admin::ResourceController
      helper_method :affiliate_partial_exists?
      before_filter :layout_options, only: [:new, :edit]

      def index
        @affiliates = Affiliate.all.page(params[:page]).per(Spree::Config[:admin_products_per_page])
      end

      protected

        def affiliate_partial_exists? partial
          return false if partial.blank? 
          Affiliate.lookup_for_partial lookup_context, partial
        end

        def layout_options
          @layout_options = Spree::Affiliate.layout_options
        end
    end
  end
end

app/controllers/spree/reffiliate_controller.rb
module Spree
  class ReffiliateController < Spree::StoreController
    def referral
      session[:referral] = params[:code]
      redirect_to root_path
    end
    def affiliate
      session[:affiliate] = params[:path]
      affiliate = Spree::Affiliate.find_by(:path => params[:path])
      if affiliate.nil? or affiliate.partial.blank? or !partial_exists affiliate.partial
        redirect_to(root_path)
      elsif partial_exists affiliate.partial
        render "spree/affiliates/#{affiliate.partial}", :layout => affiliate.get_layout
      end
    end

    private
      def partial_exists partial
        Affiliate.lookup_for_partial lookup_context, partial
      end
  end
end

app/controllers/spree/user_controller_decorator.rb
Spree::UserRegistrationsController.class_eval do
  before_filter :check_referral_and_affiliate, :only => :create
  def check_referral_and_affiliate
    params[:spree_user].merge!(:referral_code => session[:referral], :affiliate_code => session[:affiliate])
  end
end

app/views/spree/admin/affiliates/_form.html.erb
<div data-hook="admin_user_form_fields" class="row">
  <div class="alpha six columns">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, class: 'fullwidth' %>
      <%= error_message_on :user, :name %>
    <% end %>
    <%= f.field_container :partial do %>
      <%= f.label :partial, Spree.t(:partial) + " (leave blank if no partial) " %>
      <p>app/views/spree/affiliates/<%= f.text_field :partial %></p>
      <%= f.error_message_on :partial %>
    <% end %>
  </div>

  <div class="omega six columns">
    <%= f.field_container :path do %>
      <%= f.label :path, Spree.t(:path) %>
      <%= f.text_field :path, class: 'fullwidth' %>
      <%= f.error_message_on :path %>
    <% end %>
    <%= f.field_container :path do %>
      <%= f.label :layout, Spree.t(:layout) %>
      <%= select_tag 'fake_layout', options_for_select(@layout_options, selected: @affiliate.layout), class: "fullwidth #{'other' unless @layout_options.flatten.include?(@affiliate.layout)}" %>
      <%= f.text_field :layout, value: @affiliate.layout.nil? ? @layout_options.first : @affiliate.layout, class: 'fullwidth' %>
      <script>
        var fake_layout = $("#fake_layout"),
            affiliate_layout = $("#affiliate_layout");
        fake_layout.on("change", function(){
          affiliate_layout.hide();
          if ($(this).val() != '') {
            affiliate_layout.val($(this).val());
          } else {
            affiliate_layout.val('layouts/application').show().focus();
          }
        });
        if (!fake_layout.hasClass('other')) {
          affiliate_layout.hide();
        } else {
          fake_layout.val('');
        }
      </script>
      <%= f.error_message_on :layout %>
    <% end %>
  </div>
</div>

app/views/spree/admin/affiliates/edit.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_affiliate)} #{@affiliate.name}", edit_admin_affiliate_url(@affiliate) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_affiliates_list), spree.admin_affiliates_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<fieldset data-hook="admin_affiliate_edit_general_settings" class="alpha twelve columns">
  <legend><%= Spree.t(:general_settings) %></legend>

  <div data-hook="admin_affiliate_edit_form_header">
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @affiliate } %>
  </div>

  <div data-hook="admin_affiliate_edit_form">
    <%= form_for [:admin, @affiliate], as: :affiliate, url: admin_affiliate_url(@affiliate), method: :put do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_affiliate_edit_form_button">
        <%= render :partial => 'spree/admin/shared/edit_resource_links', :locals => { :collection_url => admin_affiliates_url } %>
      </div>
    <% end %>
  </div>
</fieldset>
<fieldset data-hook="admin_affiliate_edit_stats" class="alpha twelve columns">
  <legend><%= Spree.t(:statistics) %></legend>
  <table>
    <tbody>
      <tr>
        <th>Affiliate hyperlink</th>
        <td><%= text_field_tag nil, affiliate_url(@affiliate.path), onclick: 'this.select();' %></td>
      </tr>
      <tr>
        <th>Partial Status</th>
        <% if @affiliate.partial.blank? or !affiliate_partial_exists?(@affiliate.partial) %>
          <td style="color: red">Not found</td>
        <% elsif affiliate_partial_exists?(@affiliate.partial) %>
          <td style="color: green">Found</td>
        <% end %>
      </tr>
      <tr>
        <th>Referred users count</th>
        <td><%= @affiliate.referred_count %></td>
      </tr>
      <tr>
        <th>Referred orders count</th>
        <td><%= @affiliate.referred_orders.count %></td>
      </tr>
      <tr>
        <th>Orders referred</th>
        <td>
          <%= "No referred orders" if @affiliate.referred_orders.count == 0 %>
          <ol style="margin-left: 20px;">
            <% @affiliate.referred_orders.each do |user| %>
              <li><%= link_to user.email, edit_admin_user_url(user) %></li>
            <% end %>
          </ol>
        </td>
      <tr>
      <tr>
        <th>Users referred</th>
        <td>
          <%= "No referred users" if @affiliate.referred_count == 0 %>
          <ol style="margin-left: 20px;">
            <% @affiliate.referred_users.each do |user| %>
              <li><%= link_to user.email, edit_admin_user_url(user) %></li>
            <% end %>
          </ol>
        </td>
      <tr>
    </tbody>
  </table>
</fieldset>

app/views/spree/admin/affiliates/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_affiliates) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_affiliate), new_admin_affiliate_url, :icon => 'plus', :id => 'admin_new_affiliate_link' %>
  </li>
<% end %>
<% if @affiliates.any? %>
  <table class="index" id="listing_affiliates" data-hook>
    <colgroup>
      <col style="width: 15%">
      <col style="width: 20%">
      <col style="width: 15%">
      <col style="width: 15%">
      <col style="width: 15%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="admin_affiliates_index_headers">
        <th><%= Spree.t('affiliate.name') %></th>
        <th><%= Spree.t('affiliate.path') %></th>
        <th><%= Spree.t('affiliate.count') %></th>
        <th><%= Spree.t('affiliate.status') %></th>
        <th data-hook="admin_affiliates_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @affiliates.each do |affiliate|%>
        <tr id="<%= spree_dom_id affiliate %>" data-hook="admin_affiliates_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class='affiliate_name'><%=link_to affiliate.name, edit_admin_affiliate_url(affiliate) %></td>
          <td class='affiliate_path align-center'><%= affiliate_url(affiliate.path) %></td>
          <td class='affiliate_count align-center'><%= affiliate.referred_count %></td>
          <% if affiliate.partial.blank? or !affiliate_partial_exists?(affiliate.partial) %>
            <td class='affiliate_status align-center' style="color: red">Not found</td>
          <% elsif affiliate_partial_exists?(affiliate.partial) %>
            <td class='affiliate_status align-center' style="color: green">Found</td>
          <% end %>
          <td data-hook="admin_affiliates_index_row_actions" class="actions">
            <%= link_to_edit affiliate, :no_text => true %>
            <%= link_to_delete affiliate, :no_text => true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @affiliates %>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: "affiliates") %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_affiliate_path %>!
  </div>
<% end %>

app/views/spree/admin/affiliates/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_affiliate) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_affiliates_list), spree.admin_affiliates_path, :icon => 'arrow-left' %>
  </li>
<% end %>

<div data-hook="admin_affiliate_new_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @affiliate } %>
</div>

<div data-hook="admin_affiliate_new_form">
  <%= form_for [:admin, @affiliate], url: admin_affiliates_url, method: :post do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div data-hook="admin_affiliate_new_form_buttons">
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/promotions/rules/_affiliated_promotion_rule.erb
<div class="field alpha omega eight columns">
  <label><%= Spree.t('affiliates_promotion_rule.choose_affiliates') %></label><br>
  <% Spree::Affiliate.all.each do |r| %>
    <p><label><input type='checkbox' name='<%= param_prefix %>[affiliate_list][]' id='affiliate_list_<%= r.id %>' value='<%= r.id %>' <%= 'checked="checked"' if promotion_rule.affiliate_list.include?(r.id) %> /> <%= r.name %></label></p>
  <% end %>
</div>